### ISSUE TITLE
image2 plugin update breaks editing when it is used

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2975]
The image2 CKEditor plugin was updated in Mura 7.1.365. However this new version seems to rely on CKEditor 4.10.1, which adds the `editor.plugins.detectConflict` function. Mura still includes CKEditor 4.8.0.

The following error happens when trying to edit a page using image2:
`TypeError: editor.plugins.detectConflict is not a function`

**Comment by mattlevine** [comment]
I just put up a new build with 4.11
